apiVersion: apps/v1   #https://kubernetes.io/docs/reference/  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: hello
          image: "helvellyn/training"
          ports:
            - name: http
              containerPort: 8080

              apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello 
    tier: frontend 
    track: stable
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello
    tier: frontend
    track: stable  
  type: NodePort # Worked example of port forwarding / explain how portforwarding works.
   